const API_URL = "https://api-esp32.jeremypaquotdesign.workers.dev/mesures";
const REFRESH_INTERVAL_MS = 30_000;
const $ = (selector) => document.querySelector(selector);
const elements = {
  connectionStatus: $("#connectionStatus"), connectionText: $("#connectionText"),
  refreshButton: $("#refreshButton"), lastUpdate: $("#lastUpdate"),
  headerTemperature: $("#headerTemperature"), temperature: $("#temperature"),
  temperatureNote: $("#temperatureNote"), humidity: $("#humidity"), humidityNote: $("#humidityNote"),
  humidityCard: $("#humidityCard"), humidityLegend: $("#humidityLegend"), chartCanvas: $("#historyChart"),
  emptyState: $("#emptyState"), emptyTitle: $("#emptyTitle"), emptyMessage: $("#emptyMessage")
};
let historyChart = null;

function setConnectionState(state, label) { elements.connectionStatus.className = `status status-${state}`; elements.connectionText.textContent = label; }
function parseDate(value) { if (!value) return null; const normalized = /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(value) ? `${value.replace(" ", "T")}Z` : value; const date = new Date(normalized); return Number.isNaN(date.getTime()) ? null : date; }
function formatDate(value) { const date = parseDate(value); return date ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(date) : "date inconnue"; }
function formatChartTime(value) { const date = parseDate(value); return date ? new Intl.DateTimeFormat("fr-FR", { hour: "2-digit", minute: "2-digit" }).format(date) : "--:--"; }
function normalizeMeasurement(item) { if (!item || typeof item !== "object") return null; const temperature = Number(item.temperature); const humidity = Number(item.humidite); return Number.isFinite(temperature) ? { temperature, humidity: Number.isFinite(humidity) ? humidity : null, date: item.date_mesure ?? null } : null; }
function getComfortNote(type, value) { if (type === "temperature") return value < 18 ? "Ambiance fraîche" : value <= 24 ? "Température confortable" : "Ambiance chaude"; return value < 40 ? "Air plutôt sec" : value <= 60 ? "Niveau confortable" : "Air plutôt humide"; }
function showEmptyState(title, message) { elements.emptyTitle.textContent = title; elements.emptyMessage.textContent = message; elements.emptyState.hidden = false; elements.chartCanvas.hidden = true; }
function hideEmptyState() { elements.emptyState.hidden = true; elements.chartCanvas.hidden = false; }
function resetMetrics(note = "En attente d’une mesure") { elements.headerTemperature.textContent = elements.temperature.textContent = elements.humidity.textContent = "--"; elements.temperatureNote.textContent = elements.humidityNote.textContent = note; elements.lastUpdate.textContent = "Dernière mesure : aucune donnée disponible"; elements.humidityCard.hidden = false; elements.humidityLegend.hidden = false; }
function updateMetrics(measurement) { const temperature = measurement.temperature.toLocaleString("fr-FR", { maximumFractionDigits: 1 }); const hasHumidity = Number.isFinite(measurement.humidity); elements.headerTemperature.textContent = elements.temperature.textContent = temperature; elements.temperatureNote.textContent = getComfortNote("temperature", measurement.temperature); elements.humidityCard.hidden = elements.humidityLegend.hidden = !hasHumidity; elements.humidity.textContent = hasHumidity ? measurement.humidity.toLocaleString("fr-FR", { maximumFractionDigits: 1 }) : "--"; elements.humidityNote.textContent = hasHumidity ? getComfortNote("humidity", measurement.humidity) : "Non fournie par le capteur"; elements.lastUpdate.textContent = `Dernière mesure : ${formatDate(measurement.date)}`; }
function buildDatasets(measurements) { const datasets = [{ label: "Température (°C)", data: measurements.map((item) => item.temperature), borderColor: "#ffbd66", backgroundColor: "rgba(255, 189, 102, 0.12)", yAxisID: "temperatureAxis", tension: 0.36, borderWidth: 2, pointRadius: measurements.length < 12 ? 3 : 0, pointHoverRadius: 5, fill: true }]; if (measurements.some((item) => Number.isFinite(item.humidity))) datasets.push({ label: "Humidité (%)", data: measurements.map((item) => item.humidity), borderColor: "#59b7ff", backgroundColor: "rgba(89, 183, 255, 0.05)", yAxisID: "humidityAxis", tension: 0.36, borderWidth: 2, pointRadius: measurements.length < 12 ? 3 : 0, pointHoverRadius: 5 }); return datasets; }
function renderChart(measurements) { if (typeof Chart === "undefined") return showEmptyState("Graphique indisponible", "La bibliothèque du graphique n’a pas pu être chargée."); hideEmptyState(); const chronological = [...measurements].reverse(); const config = { type: "line", data: { labels: chronological.map((item) => formatChartTime(item.date)), datasets: buildDatasets(chronological) }, options: { responsive: true, maintainAspectRatio: false, interaction: { intersect: false, mode: "index" }, plugins: { legend: { display: false } }, scales: { x: { grid: { display: false } }, temperatureAxis: { position: "left", ticks: { callback: (value) => `${value}°` } }, humidityAxis: { position: "right", min: 0, max: 100, grid: { display: false }, ticks: { callback: (value) => `${value}%` } } } } }; if (historyChart) { historyChart.data = config.data; historyChart.update(); } else historyChart = new Chart(elements.chartCanvas, config); }
async function loadMeasurements() { if (loadMeasurements.busy) return; loadMeasurements.busy = true; elements.refreshButton.disabled = true; setConnectionState("loading", "Connexion…"); try { const response = await fetch(API_URL, { headers: { Accept: "application/json" }, cache: "no-store" }); if (!response.ok) throw new Error(`Erreur HTTP ${response.status}`); const payload = await response.json(); if (!Array.isArray(payload)) throw new Error("Format de réponse inattendu"); if (!payload.length) { resetMetrics(); showEmptyState("Aucune mesure disponible", "Les données apparaîtront ici dès que l’ESP32 en aura envoyé."); } else { const measurements = payload.slice(0, 50).map(normalizeMeasurement).filter(Boolean); if (!measurements.length) throw new Error("Aucune température valide"); updateMetrics(measurements[0]); renderChart(measurements); } setConnectionState("online", "API connectée"); } catch (error) { console.error(error); setConnectionState("error", "API indisponible"); showEmptyState("Connexion impossible", `${error.message}. Une nouvelle tentative aura lieu automatiquement.`); } finally { loadMeasurements.busy = false; elements.refreshButton.disabled = false; } }
elements.refreshButton.addEventListener("click", loadMeasurements); loadMeasurements(); window.setInterval(loadMeasurements, REFRESH_INTERVAL_MS);
